routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\PostsController;
use App\Http\Controllers\TagsController;
use App\Http\Controllers\UsersController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',[FrontendController::class,'index'])->name('home');
Route::get('/blogs/{post}',[FrontendController::class,'show'])->name('blogs.show');
Route::get('/blogs/category/{category}',[FrontendController::class,'category'])->name('blogs.category');
Route::get('/blogs/tags/{tag}',[FrontendController::class,'tag'])->name('blogs.tag');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');


require __DIR__.'/auth.php';

//Application Routes

Route::middleware(['auth'])->group(function(){
    Route::resource('categories',CategoriesController::class);
    Route::resource('tags',TagsController::class);
    Route::delete('posts/trash/{post}',[PostsController::class,'trash'])->name('posts.trash');
    Route::get('posts/trashed',[PostsController::class,'trashed'])->name('posts.trashed');
    Route::put('posts/restore/{post}',[PostsController::class,'restore'])->name('posts.restore');
    Route::resource('posts',PostsController::class);
});


Route::middleware(['auth', 'admin'])->group(function() {
    Route::get('/users',[UsersController::class,'index'])->name('users.index');
    Route::put('/users/{user}/make-admin',[UsersController::class,'makeAdmin'])->name('users.make-admin');
    Route::put('/users/{user}/revoke-admin',[UsersController::class,'revokeAdmin'])->name('users.revoke-admin');

});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $fillable = ['name'];

    public function posts()
    {
        return $this->hasMany(Post::class);
    }
}

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Categories\CreateCategoryRequest;
use App\Http\Requests\Categories\UpdateCategoryRequest;
use App\Models\Category;
use Illuminate\Http\Request;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $categories = Category::paginate(10);
        return view('categories.index', compact('categories')); //If the key and value of array is same then we can ony pass key using compact methods
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateCategoryRequest $request)
    {
        // 1. Validation is already done with the help of form request
        // Store the data in db
        Category::create([
            'name' => "$request->name"
        ]);
        session()->flash('success','Category created successfully!');
        return redirect(route('categories.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        //
        return view('categories.edit', compact(['category']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCategoryRequest $request, Category $category)
    {
        $category->name = $request->name;
        //$category->update(['name' => $request->name]);
        $category->save();

        session()->flash('success', 'Category Updated Successfully');
        return redirect(route('categories.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        if($category->posts()->withTrashed()->count() > 0) {
            \session()->flash('error', 'This category cannot be deleted!');
            return redirect(route('categories.index'));
        }
        $category->delete();

        session()->flash('success','category deleted successfully!');
        return redirect(route('categories.index'));
    }
}

resources/views/categories/create.blade.php
P@extends('layouts.admin-panel.app')


@section('content')



    <div class="card">
        <div class="card-header m-0">
            Add a new category
        </div>
        <div class="card-body">
            <form action="{{ route('categories.store') }}" method="POST">
                @csrf
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" name="name" id="name" class="form-control @error('name')
                                                                                is-invalid
                                                                               @enderror" value="{{ old('name') }}"
                        placeholder="Enter category name">
                    @error('name')
                        <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>
                <button type="submit" class="btn btn-outline-success">Submit</button>
            </form>
        </div>
    </div>
@endsection

resources/views/categories/edit.blade.php
@extends('layouts.admin-panel.app')


@section('content')



    <div class="card">
        <div class="card-header m-0">
            Update a category
        </div>
        <div class="card-body">
            <form action="{{ route('categories.update', $category->id) }}" method="POST">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" name="name" id="name" class="form-control @error('name')
                                                                                is-invalid
                                                                               @enderror" value="{{ old('name', $category->name) }}"
                        placeholder="Enter category name">
                    @error('name')
                        <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>
                <button type="submit" class="btn btn-outline-success">Edit Category</button>
            </form>
        </div>
    </div>
@endsection

resources/views/categories/index.blade.php
@extends('layouts.admin-panel.app')

@section('content')



    <div class="d-flex justify-content-end mb-3">
        <a href="{{ route('categories.create') }}" class="btn btn-outline-primary">Add Category</a>
    </div>
    <div class="card">
        <div class="card-header m-0">
            <h2>Categories</h2>
        </div>
        <div class="card-body">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($categories as $category)
                        <tr>
                            <td>{{ $category->name }}</td>
                            <td><a href="{{ route('categories.edit', $category->id) }}" class="btn btn-sm btn-primary">
                                    Edit</a><button type="button" class="btn btn-sm btn-danger" data-toggle="modal"
                                    data-target="#deleteModal" onclick="displayModal({{ $category->id }})">Delete
                                </button>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>


    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">

            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="" id="deleteCategory" method="POST">
                    @csrf
                    @method('DELETE')
                    <div class="modal-body">
                        Are you sure you want to delete?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-outline-danger">Delete Category</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    {{-- {{ $categories->links('vendor.pagination.bootstrap-4') }} --}}
@endsection

@section('page-level-scripts')
    <script>
        function displayModal(categoryId) {
            var url = "/categories/" + categoryId;
            $("#deleteCategory").attr('action', url);
        }
    </script>
@endsection